# Generated by Django 3.1.3 on 2022-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='Apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='Correo',
            field=models.CharField(max_length=50, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='Nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
