# Generated by Django 3.1.3 on 2022-06-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulario', '0002_auto_20220601_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='ID',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
